# Generated by Django 2.2.7 on 2019-11-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(db_index=True)),
                ('start', models.IntegerField(db_index=True)),
                ('finish', models.IntegerField()),
                ('provider', models.CharField(max_length=140)),
                ('region', models.CharField(max_length=100)),
            ],
        ),
    ]
